 platform :ios, '9.0'

target 'Swifty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  # Pods for Swifty

  # Alamofire
  pod 'Alamofire', '~> 4.7'

  # SwiftyJSON
  pod 'SwiftyJSON', '~> 4.0'

end
