 platform :ios, '9.0'

target 'SAS-SWIFTY' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SAS-SWIFTY
  # Alamofire
  pod 'Alamofire', '~> 4.7'

  # SwiftyJSON
  pod 'SwiftyJSON', '~> 4.0'

  target 'SAS-SWIFTYTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SAS-SWIFTYUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
